kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-deleter
  annotations:
    description: "Used by the platform registry app to remove project sets after their manifests have been removed from the repo monitored by Argo CD."
subjects:
  - kind: ServiceAccount
    name: project-deleter
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-deleter
