kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-deleter
  annotations:
    description: "Used by the platform registry app to remove project sets after their manifests have been removed from the repo monitored by Argo CD."
rules:
  - verbs:
      - get
      - list
      - delete
    apiGroups:
      - ""
    resources:
      - namespaces
