apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-best-effort-quota
  namespace: 59e31e-dev
  labels:
    environment: dev
    name: "59e31e"
    provisioned-by: argocd
spec:
  hard:
    pods: "3"
  scopes:
  - BestEffort
