apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-best-effort-quota
  namespace: abc123-dev-dev
  labels:
    environment: dev
    name: "abc123-dev"
    provisioned-by: argocd
spec:
  hard:
    pods: "3"
  scopes:
  - BestEffort
