apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-time-bound-quota
  namespace: 59e31e-dev
  labels:
    environment: dev
    name: "59e31e"
    provisioned-by: argocd
spec:
  hard:
    limits.cpu: "8"
    limits.memory: 32Gi
    requests.cpu: "4"
    requests.memory: 16Gi
    pods: "100"
  scopes:
  - Terminating
  - NotBestEffort
