apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: 59e31e-dev
  labels:
    environment: dev
    name: "59e31e"
    provisioned-by: argocd
spec:
  limits:
  - default:
      cpu: 250m
      memory: 1Gi
    defaultRequest:
      cpu: 50m
      memory: 256Mi
    type: Container
