apiVersion: v1
kind: ResourceQuota
metadata:
  name: snapshot-quota
  namespace: abc123-dev
  labels:
    environment: dev
    name: "abc123-dev"
    provisioned-by: argocd
spec:
  hard:
    count/volumesnapshots.snapshot.storage.k8s.io: "5"
