apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-netapp-block-extended-quota
  namespace: abc123-dev-dev
  labels:
    environment: dev
    name: "abc123-dev"
    provisioned-by: argocd
spec:
  hard:
    netapp-block-extended.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    netapp-block-extended.storageclass.storage.k8s.io/requests.storage: 0
