apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-netapp-block-standard-quota
  namespace: 59e31e-dev
  labels:
    environment: dev
    name: "59e31e"
    provisioned-by: argocd
spec:
  hard:
    netapp-block-standard.storageclass.storage.k8s.io/persistentvolumeclaims: "60"
    netapp-block-standard.storageclass.storage.k8s.io/requests.storage: 64Gi
