apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-netapp-file-standard-quota
  namespace: abc123-dev-dev
  labels:
    environment: dev
    name: "abc123-dev"
    provisioned-by: argocd
spec:
  hard:
    netapp-file-standard.storageclass.storage.k8s.io/persistentvolumeclaims: "60"
    netapp-file-standard.storageclass.storage.k8s.io/requests.storage: 64Gi
