apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: abc123-dev
  labels:
    environment: dev
    name: "abc123-dev"
    provisioned-by: argocd
spec:
  hard:
    persistentvolumeclaims: "60"
    requests.storage: 64Gi
