---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations: {}
  labels:
    devops.gov.bc.ca/argocd-app-shared: team1-app2-dev
  name: app2-network-policy
  namespace: iankwatts-dev
spec:
  ingress:
    - ports:
        - port: 9999
          protocol: TCP
    - from:
        - podSelector: {}
  podSelector: {}
  policyTypes:
    - Ingress
