apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "59e31e"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: "tenants/59e31e/"
    repoURL: "https://github.com/iankwatts/argocd-team1.git"
    targetRevision: "HEAD"
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
