apiVersion: batch/v1
kind: Job
metadata:
  name: test-patch
  #generateName: test-patch-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      imagePullSecrets:
        - name: dockerhub-bcgovdevops
      containers:
      - name: test-patch
        image: docker.io/bcgovdevops/utility-server:latest
        command:
          - "oc"
          - "-n"
          - "iankwatts-dev"
          - "get"
          - "pods"
          - "&&"
          - "date"
      restartPolicy: Never
  backoffLimit: 4
