name: Testing

on:
  pull_request:
    types:
      - closed
    paths:
      - "testing/*"

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Test file deletion
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: echo "this is a test:${BRANCH_NAME}"
